SPHTech-Platform/terraform-aws-opensearch

modules/ingestion/pipeline/data.tf, modules/resource-mgt/ism.tf, modules/resource-mgt/locals.tf, modules/resource-mgt/variables.tf
We want to have the ability to map ISM policies to indices in cases where an ISM policy already exists. This enables us to do that. It is observed that in some situations the ISM policy creation API call times out but the policy does get created. This can also help us there too.
=> feat: ism policy mapping should work with existing policies

modules/ism/template/README.md, modules/ism/template/main.tf, modules/ism/template/ouputs.tf
Elasticsearch v7.8 onwards uses the `_index_template` API which is relatively newer. We are switching the resource type for ISM template to make it compatible with Opensearch
https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/composable_index_template
=> fix: elasticsearch v7.8+ uses new ism template api

main.tf, variables.tf
additional auto tune options is required to create new opensearch domains. If `rollback_on_disable` is not declared, terraform apply will have the following issue:
`Error: modifying config for OpenSearch Domain: ValidationException: 1 validation error detected: Value '' at 'autoTuneOptions.rollbackOnDisable' failed to satisfy constraint: Member must satisfy enum value set: [DEFAULT_ROLLBACK, NO_ROLLBACK]`
`rollback_on_disable` also requires `maintenance_window` if `DEFAULT_ROLLBACK` is selected, so added as a dynamic block
=> add additional options for auto tune

README.md, examples/opensearch/outputs.tf, outputs.tf
Opensearch does not use Kibana and this field has been deprecated so it can be removed
=> chore: remove deprecated kibana endpoint

modules/ingestion/iam/data.tf
Ingestion pipeline IAM role only needs read/write permissions to Opensearch
=> restricted iam policy for ingestion pipeline

examples/ingestion/main.tf, modules/ingestion/pipeline/README.md, modules/ingestion/pipeline/pipeline.tf, modules/ingestion/pipeline/variables.tf, modules/ingestion/pipeline/versions.tf
Opensearch ingestion pipelines now support buffering.
References: 
- https://aws.amazon.com/blogs/big-data/introducing-persistent-buffering-for-amazon-opensearch-ingestion/
- https://registry.terraform.io/providers/hashicorp/awscc/0.67.0/docs/resources/osis_pipeline#nested-schema-for-buffer_options
=> support for buffering in ingestion pipelines

README.md, cloudwatch.tf, variables.tf
https://github.com/SPHTech-Platform/terraform-aws-opensearch/issues/27
=> variable for log group retention period

examples/ingestion/versions.tf, modules/ingestion/pipeline/README.md, modules/ingestion/pipeline/locals.tf, modules/ingestion/pipeline/outputs.tf, modules/ingestion/pipeline/pipeline.tf, modules/ingestion/pipeline/variables.tf, modules/ingestion/pipeline/versions.tf
Migration of Opensearch ingestion pipeline resource from AWSCC to AWS TF provider.
References:
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/osis_pipeline
=> migrate osis pipeline to aws from awscc

README.md, data.tf, examples/opensearch/main.tf, main.tf, outputs.tf, variables.tf, versions.tf
`aws_opensearch_vpc_endpoint` resource is available in AWS provider versions `>= 5.13` so adding this in.
Reference: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_vpc_endpoint
=> feat: opensearch vpc endpoint

modules/dashboard/index-pattern/README.md, modules/dashboard/index-pattern/main.tf, modules/dashboard/index-pattern/outputs.tf, modules/dashboard/index-pattern/variables.tf, modules/dashboard/index-pattern/versions.tf
Submodule to create index patterns in Opensearch.
References:
- https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/dashboard_object
=> feat: index pattern submodule

modules/ingestion/pipeline/README.md, modules/ingestion/pipeline/cloudwatch.tf, modules/ingestion/pipeline/data.tf, modules/ingestion/pipeline/pipeline.tf, modules/ingestion/pipeline/variables.tf
Making KMS key encryption optional for ingestion pipeline. Use AWS owned key by default
=> make kms key optional for pipeline logs

examples/role/main.tf, examples/role/providers.tf, examples/role/versions.tf, modules/dashboard/tenant/README.md, modules/dashboard/tenant/main.tf, modules/dashboard/tenant/outputs.tf, modules/dashboard/tenant/variables.tf, modules/dashboard/tenant/versions.tf, modules/role/README.md, modules/role/main.tf, modules/role/outputs.tf, modules/role/variables.tf, modules/role/versions.tf
- Dashboard tenant
- Opensearch role with mapping
- Example with docs
=> feat: dashboard tenant and opensearch role submodules

README.md, main.tf, variables.tf
Adds Cognito options into Opensearch. Reference: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain#cognito_options
=> Add Cognito Options into Opensearch

alarms.tf
Renaming CW alarm name for Opensearch kms key being inaccessible
=> fix: aos_key_inaccessible alarm name

modules/dashboard/index-pattern/README.md, modules/dashboard/index-pattern/main.tf, modules/dashboard/index-pattern/variables.tf, modules/dashboard/index-pattern/versions.tf
Opensearch provider `v2.3` now supports multi-tenancy when creating dashboard objects. We can use this to create index patterns in individual tenants.
References:
- https://github.com/opensearch-project/terraform-provider-opensearch/releases/tag/v2.3.0
- https://github.com/opensearch-project/terraform-provider-opensearch/pull/184
=> feat: multi-tenancy support for dashboard objects

README.md, alarms.tf
Cloudwatch alarms should have domain name as a prefix to uniquely identify them.
=> unique cloudwatch alarms naming

alarms.tf
Cloudwatch alarm for got to warm migration failures.
Reference: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cloudwatch-alarms.html
=> hot to warm migration cloudwatch alarm

alarms.tf
Correcting the create flag for Cloudwatch metric alarms to `create_metric_alarm` instead of `create`
Reference: https://github.com/terraform-aws-modules/terraform-aws-cloudwatch/tree/master/modules/metric-alarm#input_create_metric_alarm
=> fix: create flag for cloudwatch metric alarms

examples/notification/main.tf, examples/notification/providers.tf, examples/notification/versions.tf, modules/channel/slack/README.md, modules/channel/slack/main.tf, modules/channel/slack/outputs.tf, modules/channel/slack/variables.tf, modules/channel/slack/versions.tf, modules/monitor/README.md, modules/monitor/main.tf, modules/monitor/outputs.tf, modules/monitor/variables.tf, modules/monitor/versions.tf
Submodules for creating slack channels and monitors. 
https://sph.atlassian.net/browse/PFMENG-2237
References:
- https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/channel_configuration
- https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/monitor
=> feat: slack channel and monitor submodules

alarms.tf
Recommendations for AWS Support:
-- ClusterIndexWritesBlocked is >= 1 for 5 minutes, 1 consecutive time
-- Consider Changing period to 60s (1 Min)
-- Consider Changing DatapointstoAlarm to 5 out 5
=> change period for cluster writes blocked

modules/collection/README.md, modules/collection/endpoint.tf, modules/collection/locals.tf, modules/collection/main.tf, modules/collection/outputs.tf, modules/collection/variables.tf, modules/collection/versions.tf
Submodule for creating Opensearch serverless collections.
References:
- https://github.com/terraform-aws-modules/terraform-aws-opensearch/tree/master/modules/collection
=> feat: serverless collection submodule

.pre-commit-config.yaml, .tflint.hcl, README.md, examples/opensearch/main.tf, examples/opensearch/versions.tf, main.tf, variables.tf, versions.tf
Support for dedicated coordinator nodes.
References:
- https://docs.aws.amazon.com/opensearch-service/latest/developerguide/Dedicated-coordinator-nodes.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain#node_options-1
=> feat: support coordinator nodes

README.md, main.tf, variables.tf
- adds `multi_az_with_standby_enabled` flag onto `cluster_options`
=> add support for multi-az with standby

alarms.tf
References: 
- https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cloudwatch-alarms.html
- https://github.com/zoitech/terraform-aws-opensearch-cloudwatch-metrics/blob/56bcf171bfd708f71a3dfd95bab89e677ab1c4d7/cloudwatch_metric_alarms.tf#L38
=> cloudwatch alarm for nodes having <= 25% free storage space

.pre-commit-config.yaml, .terraform-docs.yaml, .tflint.hcl, README.md, alarms.tf, examples/ingestion/main.tf, examples/ingestion/versions.tf, examples/opensearch/versions.tf, iam.tf, modules/ingestion/iam/README.md, modules/ingestion/iam/iam.tf, modules/ingestion/iam/versions.tf, modules/ingestion/pipeline/README.md, modules/ingestion/pipeline/locals.tf, modules/ingestion/pipeline/versions.tf, versions.tf
-  Support for AWS provider v6
- Upgrading upstream AWS modules
- Updated pre-commit hooks
=> support for aws provider v6 with upstream aws modules upgrade
